### ISSUE TITLE
Unable to download models

### ISSUE THREAD

**Issue by trotrem** [Lambda-3/Indra#69]
I tried running ./downloader.sh esa-en-wiki-2018
to download the model and try Indra, but it is not connecting.
(I also tried with other models)

Are they still available?

**Comment by julsal** [comment]
Hi @trotrem, thanks for your message. Unfortunately, the server financed by our partner is not available anymore. However, you can get the esa English model from [this link](https://drive.google.com/drive/folders/1PKoZVuhAy9EK8wRNAgk7tCEIV6EnWWlS?usp=sharing). Please, check the script `download.sh` to understand how to salve it in order to allow `indra` to read its content.
